[package]
name = "ashypass-native-host"
description = "Ashy Pass — native messaging host for browser extensions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "ashypass-native-host"
path = "src/main.rs"

[dependencies]
ashypass-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
